apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
type: Opaque
data:
  JWT_SECRET: "eW91LWNhbi1yZXBsYWNlLXRoaXMtd2l0aC15b3VyLW93bi1zZWNyZXQ="
  USER_MONGODB_URI: "bW9uZ29kYitzcnY6Ly9kYW5pZWxsb2g6RkFXRmJzRlhTeXJqNWJBekBwZWVycHJlcC51MmxpYi5tb25nb2RiLm5ldC9wZWVycHJlcA=="
  GMAIL_USER: "cGVlcnByZXAzOEBnbWFpbC5jb20K"
  GMAIL_PASS: "Y3JheiBza2poIGVjZXYgcHhpbQo="
