version: '3'
services:

  frontend:
    image: g38-frontend:latest
    container_name: g38-frontend
    env_file:
      - .env
    ports:
      - "${NEXT_PUBLIC_FRONTEND_PORT}:${NEXT_PUBLIC_FRONTEND_PORT}"

  user-mongodb:
    image: mongo:latest
    container_name: user-service-mongodb
    # expose port for testing purposes or to view database in MongoDB Compass
    ports:
      - "27017:27017"
    volumes:
      - ./user-mongo-data:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USER_MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${USER_MONGO_INITDB_ROOT_PASSWORD}
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
    command: /bin/sh -c 'if [ -z "$USER_MONGODB_URI" ]; then echo "Starting MongoDB..."; /usr/local/bin/docker-entrypoint.sh mongod; else echo "USER_MONGODB_URI is set. Shutting down."; exit 1; fi'
    restart: no

  g38-user-service:
    image: delishad21/g38-user-service:latest
    container_name: user-service
    env_file:
      - .env  # Loads environment variables from .env file
    environment:
      - USER_MONGODB_URI=${USER_MONGODB_URI:-mongodb://${USER_MONGO_INITDB_ROOT_USERNAME}:${USER_MONGO_INITDB_ROOT_PASSWORD}@user-mongodb:27017/user-service?authSource=admin}  # Fallback to local MongoDB if MONGODB_URI is not set
    ports:
      - "${USER_PORT}:${USER_PORT}"  # Bind port using env variable
    depends_on:
      - user-mongodb

  question-mongodb:
    image: mongo:latest
    container_name: question-service-mongodb
    # expose port for testing purposes or to view database in MongoDB Compass
    ports:
      - "27018:27017"
    volumes:
      - ./question-mongo-data:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${QUESTION_MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${QUESTION_MONGO_INITDB_ROOT_PASSWORD}
    entrypoint: /bin/sh -c 'if [ -z "$QUESTION_MONGODB_URI" ]; then echo "Starting MongoDB..."; /usr/local/bin/docker-entrypoint.sh mongod; else echo "QUESTION_MONGODB_URI is set. Shutting down."; exit 1; fi'
    restart: no

  g38-question-service:
    image: delishad21/g38-question-service:latest
    container_name: question-service
    env_file:
      - .env  # Loads environment variables from .env file
    environment:
      - QUESTION_MONGODB_URI=${QUESTION_MONGODB_URI:-mongodb://${QUESTION_MONGO_INITDB_ROOT_USERNAME}:${QUESTION_MONGO_INITDB_ROOT_PASSWORD}@question-mongodb:27017/question-service?authSource=admin}  # Fallback to local MongoDB if MONGODB_URI is not set
    ports:
      - "${QUESTION_PORT}:${QUESTION_PORT}"  # Bind port using env variable
    depends_on:
      - question-mongodb
