version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-question-service
    volumes:
      - ./mongo-data:/data/db
    env_file:
      - .env

  g38-question-service:
    image: g38-question-service:latest
    container_name: question-service
    env_file:
      - .env  # Loads environment variables from .env file
    ports:
      - "${QUESTION_PORT}:${QUESTION_PORT}"  # Bind port using env variable
    depends_on:
      - mongodb
