apiVersion: v1
kind: Secret
metadata:
  name: collab-secrets
type: Opaque
data:
  COLLAB_MONGODB_URI: "bW9uZ29kYitzcnY6Ly9kYW5pZWxsb2g6RkFXRmJzRlhTeXJqNWJBekBwZWVycHJlcC51MmxpYi5tb25nb2RiLm5ldC9wZWVycHJlcA=="
